name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./src/Rgom.FileMetadata.Sidecar/Rgom.FileMetadata.Sidecar.csproj
    - name: Build
      run: dotnet build ./src/Rgom.FileMetadata.Sidecar/Rgom.FileMetadata.Sidecar.csproj -c Release --no-restore
    - name: Publish
      run: dotnet publish ./src/Rgom.FileMetadata.Sidecar/Rgom.FileMetadata.Sidecar.csproj -c Release -p:PublishTrimmed=true -r win-x64 -o ./publish
    - name: Automatic Releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ./publish/fmdsc.exe
